name: main.yml

on:
  pull_request:
    types: [ assigned, opened, reopened ]
  issue_comment:
    types: [created]
    branches: [ main ]
    
env:
  PR: ${{ github.event.pull_request.title }} 
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  
jobs:
  build:
    #if: github.event.pull_request.merged == true
    if: ${{ github.event_name == 'pull_request' || (github.event_name == 'issue_comment' && github.event.comment.body == '/Build Trigger') }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install

    #- name: Run the cypress tests
      #run: npm test

    - name: Build
      run: npm run build

    - name: Deploy
      uses: reggionick/s3-deploy@v3
      with:
        folder: build
        bucket: ${{ secrets.S3_BUCKET }}
        bucket-region: ${{ secrets.S3_BUCKET_REGION }}
        dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
        invalidation: /
        delete-removed: true
        no-cache: true
        private: true
